modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/davidjjung/blastedbarrens/issues"
license = "MIT License"

[[mods]]
modId = "blasted_barrens"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "blasted_barrens:ashen_sand"
configBackground = "minecraft:textures/block/dirt.png"
authors = "DavigJ"
credits = "Snake Block, Musicano"
displayURL = "https://modrinth.com/project/blasted-barrens"
displayName = "Blasted Barrens"
description = '''
    This mod adds a semi-fantastical biome, the Blasted Barrens.
    '''

[[dependencies.blasted_barrens]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blasted_barrens]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blasted_barrens]]
modId = "blueprint"
mandatory = true
versionRange = "[7.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blasted_barrens]]
modId = "clayworks"
mandatory = false
versionRange = "[3.0.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blasted_barrens]]
modId = "fog"
mandatory = false
versionRange = "[1.5.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blasted_barrens]]
modId = "supplementaries"
mandatory = false
versionRange = "[1.20-3.1.41,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blasted_barrens]]
modId = "foglooksmodernnow"
mandatory = false
versionRange = "[1.2.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blasted_barrens]]
modId = "create"
mandatory = false
versionRange = "[6.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blasted_barrens]]
modId = "upgrade_aquatic"
mandatory = false
versionRange = "[6.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blasted_barrens]]
modId = "pehkui"
mandatory = false
versionRange = "[3.8.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blasted_barrens]]
modId = "immersiveoverlays"
mandatory = false
versionRange = "[1.5.0,)"
ordering = "AFTER"
side = "BOTH"